# Generated by Django 3.1.5 on 2021-01-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_name', models.CharField(max_length=50, verbose_name='Name')),
                ('pc_value', models.FloatField(max_length=10, verbose_name='Value')),
                ('pc_description', models.CharField(max_length=500, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
    ]
