# Generated by Django 3.1.5 on 2021-01-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricecard',
            name='pc_description',
            field=models.TextField(max_length=500, verbose_name='Description'),
        ),
    ]
