# Generated by Django 3.1.5 on 2021-01-17 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_auto_20210118_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricecard',
            name='pc_description',
        ),
    ]
