# Generated by Django 3.1.5 on 2021-01-17 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmssystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmsslider',
            old_name='cms_img',
            new_name='cms_image',
        ),
    ]
