# Generated by Django 3.1.5 on 2021-01-18 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmsystem', '0002_auto_20210118_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='request_plan',
            new_name='request_value',
        ),
    ]
