# Generated by Django 3.1.5 on 2021-01-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmsystem', '0005_auto_20210119_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_plan',
            field=models.CharField(max_length=200, verbose_name='Plan'),
        ),
    ]
