# Generated by Django 3.1.5 on 2021-01-18 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmsystem', '0007_auto_20210119_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Data'),
        ),
        migrations.CreateModel(
            name='CommentCrm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='Comment')),
                ('comment_dt', models.DateTimeField(auto_now=True, verbose_name='Data')),
                ('comment_binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmsystem.request', verbose_name='Request')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
